"""add product auth references table

Revision ID: 26236a7011fe
Revises: 4e98db49ef98
Create Date: 2026-03-05 23:19:48.087768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26236a7011fe'
down_revision = '4e98db49ef98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_auth_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('brand_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('label_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_auth_references_id'), 'product_auth_references', ['id'], unique=False)
    op.create_index(op.f('ix_product_auth_references_ref_code'), 'product_auth_references', ['ref_code'], unique=True)
    op.alter_column('product_tags', 'product_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('idx_product_tags_product_id'), table_name='product_tags')
    op.drop_index(op.f('idx_product_tags_tag_id'), table_name='product_tags')
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.alter_column('tags', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_product_tags_tag_id'), 'product_tags', ['tag_id'], unique=False)
    op.create_index(op.f('idx_product_tags_product_id'), 'product_tags', ['product_id'], unique=False)
    op.alter_column('product_tags', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_product_auth_references_ref_code'), table_name='product_auth_references')
    op.drop_index(op.f('ix_product_auth_references_id'), table_name='product_auth_references')
    op.drop_table('product_auth_references')
    # ### end Alembic commands ###
