"""add ingredient_highlights to products

Revision ID: 8f9b60997353
Revises: d1ffe084bd94
Create Date: 2025-12-18 17:11:26.240935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f9b60997353'
down_revision = 'd1ffe084bd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ingredient_highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ingredient_highlights')
    # ### end Alembic commands ###
